### ISSUE TITLE
Compute dynamic defaults

### ISSUE THREAD

**Issue by uvsmtid-gs** [uvsmtid/argrelay#8]
Selection of some `data_envelope`-s may provide (compute-able) defaults to find subsequent ones.

For example, when `ServiceEnvelopeClass.ClassCluster` ~ `prod` (not `dev`) is selected
for a function which performs remote login,
it makes sense to set `ServiceArgType.AccessType` ~ `ro` as default.
Conversely, if it is ~ `dev` (not `prod`), `ServiceArgType.AccessType` should be assumed as `rw` by default.

Such defaults cannot be adquately assigned statically because it depends on the function (plugin logic),
knowledge what will be done with these `data_envelope`-s, and should be extensible (again, by plugins).

The idea is to add a server-side hook for `InvocatorPlugin`
which inspects currently selected `data_envelope`-s
and computes these defaults for the next `data_envelope`-s.

**Comment by uvsmtid** [comment]
The server-side hook is currently called `run_fill_control` (implemented by `PluginType.DelegatorPlugin`).

Specifically the example above is implemented as:
https://github.com/argrelay/argrelay/blob/v0.5.2.final/src/argrelay/custom_integ/ServiceDelegator.py#L277
